# -*- coding: utf-8 -*-

columns2 = ["Cultivo de arroz",
"Cultivo de trigo",
"Cultivo de outros cereais",
"Cultivo de vegetais e frutas",
"Cultivo de oleaginosas",
"Cultivo de cana-de-açúcar",
"Cultivo de algodão herbáceo e outras fibras",
"Outras lavouras",
"Criação de bovinos",
"Criação de outros animais",
"Produção de leite cru",
"Produção de lã",
"Produção florestal",
"Pesca",
"Beneficiamento de arroz ",
"Extração de carvão mineral",
"Extração de petróleo",
"Extração de gás natural",
"Extração de outros recursos minerais",
"Fabricação de produtos de carne bovina",
"Fabricação de outros produtos de carne",
"Fabricação de óleos e gorduras vegetais",
"Lacticínios",
"Fabricação e refino de açúcar",
"Fabricação de outros produtos alimentícios",
"Fabricação de bebidas e produtos do fumo",
"Fabricação de produtos têxteis",
"Confecção de artigos do vestuário e acessórios",
"Preparação de couros e fabricação de artefatos de couro",
"Fabricação de produtos de madeira",
"Fabricação de celulose, papel e produtos de papel",
"Fabricação de coque, refino de petróleo, elaboração de combustíveis nucleares e produção de álcool",
"Fabricação de produtos químicos, de borracha e de material plástico",
"Fabricação de produtos de minerais não metálicos",
"Metalurgia",
"Metalurgia dos metais não-ferrosos",
"Fabricação de produtos de metal ",
"Fabricação e montagem de veículos automotores, reboques e carrocerias",
"Fabricação de outros equipamentos de transporte",
"Fabricação de máquinas, aparelhos e materiais elétricos",
"Fabricação de máquinas e equipamentos",
"Fabricação de produtos diversos",
"Geração, transmissão e distribuição de energia elétrica",
"Produção e distribuição de combustíveis gasosos",
"Água e esgoto",
"Construção",
"Comércio",
"Transporte terrestre e atividades auxiliares",
"Transporte aquaviário",
"Transporte aéreo",
"Informação e comunicação",
"Atividadesde serviços financeiros",
"Seguros",
"Outros serviços prestados às empresas",
"Artes, cultura, esporte, recreação e outros serviços",
"Serviços públicos",
"Atividades imobiliárias",
"Desemprego"]

columns=["Arroz",
"Trigo",
"Cereais",
"Vegetais e Frutas",
"Oleaginosas",
"Cana",
"Algodão",
"Lavouras",
"Bovinos",
"Out. animais",
"Leite cru",
"Lã",
"Florestal",
"Pesca",
"Ben. De arroz",
"Carvão",
"Petróleo",
"Gás",
"Extração",
"Carne",
"Outros carne",
"Fab. Óleos",
"Lacticínios",
"Açúcar",
"Fab. Alimentos",
"Fab. Bebidas",
"Texteis",
"Vestuário",
"Couros",
"Madeira",
"Celulose",
"Refino e comb.",
"Quím. Plasticos",
"Não-metálicos",
"Metalurgia",
"Não-ferrosos",
"Prod. Metal",
"Veículos",
"Out. transp.",
"Máq e elétricos",
"Máq e equip.",
"Diversos",
"Energia elét.",
"Comb. Gasosos",
"Água e esgoto",
"Construção",
"Comércio",
"Transporte",
"Aquaviário",
"Aéreo",
"Inf. E Com.",
"Financeiro",
"Seguros",
"Serviços empresas",
"Artes, esporte",
"Públicos",
"Imobiliários"]
